#+title: Experience

Where I deal with systems—sometimes they cooperate, usually they don’t.

* Jump Trading Group
/Software Engineer Intern/
- Incoming Spring 2026

* NVIDIA -- CUDA Perf.
/Systems Software Engineer Intern/

**August 2025 - December 2025**

- Developed an optimization to localize launch buffers across chiplets to reduce latency
- Building architectural models for various SOL metrics such as PCIe bandwidth to measure during Si. bring-up
- Automating perf profiling workflow for Si. bring-up

* AWS Annapurna Labs -- Graviton Sw. Perf.
/Software Engineer Intern/

**May 2025 - August 2025**

- Designed in-memory profiling tool to identify instruction hotspots on ARM cores with SPE.
- Utilized SPE to create a low overhead monitoring mechanism with < $2\%$ memory usage and < $1\%$ CPU usage.
- Integrated tool into opensource [[https://github.com/aws/aperf][APerf]] repository


* ECE 391 (Operating Systems)
/Course Assistant/

**December 2024 - May 2025**
- Worked on a nightly autograder for MP1 (first major student assig2nment of semester)
- Helped redesign robust autograder that automatically interfaces with GDB and student ELFs
- Ran midterm review sessions for 100+ students
- Developing final OS project to incorporate new features and improving documentation

* Omni RPA
/Software Engineer Intern/

**May 2024 - August 2024**
- Built a network transfer cost optimizer for an orchestrator using Go and Nebula
- Designed large-scale graph models to represent pricing and performance models in Snowflake and Nebula DB
- Constructed scalable microservices to automate downloading, parsing, and uploading cloud provider data

[[./index.org][Home]]
