#+title: Projects

Just some projects I’ve enjoyed building along the way.

*** [[./static/paper.pdf][RVipc]]
- RISC-V extension to allow piping information between physical RISC-V cores.
- Uses a set of hardware FIFOs and a handshake protocol to establish communication.
- Avoids the cache coherence latency and trap entry expense incurred by shared memory and pipes.
- Modified gem5 and wrote kernel specific code to leverage hardware and software ipc.

*** [[./static/quicksend.pdf][QuickSend]]
- Reverse engineering current software-transparent compression mechanisms involved in sending workloads to GPU.
- Implementing academica compression algorithms and benchmarking with for power, area, and performance analysis.
- Introduced novel compression mechanisms and analyze power, area, and performance tradeoffs.
- Achieved $2\times$ compression as Intel iGPU 8th Generation.

*** RISC-V Operating System
- RISC-V Unix-like OS with paging, filesystem, devices, system calls, and a pre-emptive round robin scheduling
- Developed a virtio block driver, cryptography driver, and entropy driver
- Kernel supports pipes between processes and argument passing according to POSIX standards
- 2nd place in OS design competition in ECE department with 100+ teams

*** CUDA-based LeNet CNN Network
- Developed and optimized forward pass of LeNet CNN Network
- Designed and benchmarked with modern accelerator features such as streams and tensor cores using nsys and ncu
- Achieved lossless speedups of 70.45% from base trivial GPU implementation
- Used cuBLAS, half precision floating points, and constant memory on A100 GPUs to improve cache and SM usage

[[./index.org][Home]]