#+title: Research Experience

Breaking things in theory is safer than in production... 

* [[./static/ustt.pdf][uSTT]] -- SLICE @ Berkeley Architecture Research
- /Research under Prof. Chris Fletcher/
- Research to realize $\texttt{STT}$, a micro-architectural protection mechanism for side-channel attacks.
- Modified RTL and verification to make the RAT (Rename Alias Table) and $\texttt{STT}$ logic stateful.
- Created high-level architecture for a pipelined design to reduce delay.

* RTeAAL -- SLICE @ Berkeley Architecture Research
- /Also with Prof. Chris Fletcher/
- Rewriting RTL simulators as tensor problems for new opportunities.
- Formally describing RTL simulation as Einsums.
- Creating scheduler to optimize computation graph to reduce heterogeneity layers and reduce branch misdirection.

* [[./static/act-arxiv.pdf][ACT]] -- ADAPT Lab
- /Research under Prof. Charith Mendis/
- Framework that automates the generation of sound compiler backends for accelerators.
- Evaluated system with synthetic and industry kernels in HLO.
- Developed first module which entailed parsing user supplied HLO into egraphs.

[[./index.org][Home]]
