=#ifndef CPP_FUNC_TEMPLATE_TYPE_INF_H_=

=#define CPP_FUNC_TEMPLATE_TYPE_INF_H_=
#+title: C++ Function Template Type Inference 

C++'s type system, particularly for templates and =auto=, were rather elusive to me. I wasn't able to find a great *concise* resource for understanding the *reasoning* for the type deduction rules. This is my best understanding of why the mechanism was designed the way it was. If there's any errors, please let me know I'd love to learn :).

Suppose we have something like
#+BEGIN_SRC cpp
template <typename T>
void foo(T arg) {
  // ...
}

template <typename T>
void foo2(T& arg) {
  // ...
}

int main() {
  const int x = 42;
  foo(x);
  foo2(x);
}
#+END_SRC

How exactly are the types for =T= and =arg= deduced? Contrary to what seems obvious, =T= for =foo= is deduced as =int=, and =T= for =foo2= is deduced as =const int=. Why?

First, I'll summarize the rules. Effective Modern C++ is an excellent book to deeply learn this material. I will conform to the terminology used there. The type of =arg= is referred to as =ParamType=, and the type of =x= when we call the function is the call site.


- Case 1: =ParamType= is a reference or a pointer.
The reference/pointer is then stripped from the call site (if it exists). If =ParamType= is a =const= reference/pointer, then =const= is also stripped from the call site (if it exists). *Only* the top-level =&/*= and =const= are stripped.

- Case 2: =ParamType= is a pass-by-value.
Then top-level CV-qualifiers (=const= and =volatile=) and refs are stripped.

- Case 3: =ParamType= is a universal reference.
If call site is an l-value ref, then =T= is a ref. If call site is an r-value ref, then =T= is a non-ref type.

This makes sense so far, but it begs the question *why are the rules the way they are*. This is my rationale for it.

If =ParamType= is a ref, there is no benefit to the call site having a ref. A reference to a reference to an int variable, is just a reference to the same int variable. Moreover, using =int &&= is actually interperated as an r-value reference, and will break semantics. If we call =foo(x)=, we don't want the compiler thinking =x= is an r-value and move it. Therefore, we strip the call site reference. The exact same logic applies for a pointer. A pointer to a pointer to an int variable is not the semantics we want if the callsight is =foo(int*)= and =ParamType= is =const T*=. If we didn't strip references/pointers, we would get =T= as =int *= and =ParamType= as =const int* *=, which is clearly not what we want.

If =ParamType= is has a =const= ref, and call site has a const, we can also strip the call site const. It is extra redundancy since =const const int x= doesn't add any additional meaning than =const int x=. 

If =ParamType= is a pass-by-value, then we don't actually need any references or CV-qualifiers. Pass-by-value makes a mutable copy of the argument. So, just because the call site can't be modified, it doesn't mean the argument in the function can. Similarily, just because the call site requires =volatile= doesn't mean the argument in the function does since it is a copy of the variable. Abiding by the call site CV-qualifiers is overly restsrictive and unintuitive. *However*, if the call site were =const int * const &=, this will get stripped to =const int *=. Notice how not all the =const= s were stripped. *Only* the top-level CV-qualifiers and references can be stripped.

Lastly, =ParamType= being a universal reference has special rules. The purpose of the universal reference is to allow perfect forward. For example,


#+BEGIN_SRC cpp
template <typename T>
void wrapper(T&& arg) {
  foo(std::forward<T>(arg));
}

void foo(int& arg) {}
void foo(int&& arg) {}
#+END_SRC

I want to ensure that if I call =wrapper= with =wrapper(5)= versus =wrapper(x)=, the right overloaded =foo= is called. This is important for performance considerations, as an r-value can be moved, and can allow highly specialized logic.

This is where universal references come in. If I call =wrapper= with =int&= (an l-value), =T= is deduced as an =int&=. Due to reference collapsing, =ParamType= goes from =int& &&= to =int&=. This is precisely a reference to an l-value! We have preserved l-value call sites. If I call =wrappper= with =wrapper(5)=, with the call site being =int &&=, =T= is deduced as an =int=. Then, =ParamType= is deduced as =int &&=, preserving the r-value call site! This will later correctly overload =foo= and ensure correct code flow.

Hopefully this helps with understanding how types are deduced in function templates a bit better. There's a whole other set of rules for =auto=, lambdas, init-lambdas, etc (maybe more blogs?!).

=#endif // CPP_FUNC_TEMPLATE_TYPE_INF_H_=

[[./blogs.org][Blog]]
