name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 29.3

      - name: Run the build script
        run: ./build.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build_out   # make sure this matches your build output folder

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4